version: "3.7"

services:

    podcast-fetch-transcript:
        image: gcr.io/mcback/podcast-fetch-transcript:latest
        init: true
        stop_signal: SIGKILL
        environment:
            MC_PODCAST_GC_AUTH_JSON_BASE64: "${MC_PODCAST_GC_AUTH_JSON_BASE64}"
            MC_PODCAST_FETCH_TRANSCRIPT_RUN_COSTLY_TEST: "${MC_PODCAST_FETCH_TRANSCRIPT_RUN_COSTLY_TEST}"
        expose:
            # "test_full_chain.py" test server's port
            - 8080
        volumes:
            - type: bind
              source: ./bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./src/
              target: /opt/mediacloud/src/podcast-fetch-transcript/
            - type: bind
              source: ./tests/
              target: /opt/mediacloud/tests/
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/
        depends_on:
            - podcast-fetch-episode
            - podcast-submit-operation
            # No "podcast-poll-due-operations" as we'll just go ahead and fetch it ourselves
            - postgresql-pgbouncer
            - rabbitmq-server

    podcast-fetch-episode:
        image: gcr.io/mcback/podcast-fetch-episode:latest
        init: true
        stop_signal: SIGKILL
        environment:
            MC_PODCAST_GC_AUTH_JSON_BASE64: "${MC_PODCAST_GC_AUTH_JSON_BASE64}"
            MC_PODCAST_FETCH_EPISODE_BUCKET_NAME: "${MC_PODCAST_FETCH_EPISODE_BUCKET_NAME}"
            MC_PODCAST_FETCH_EPISODE_PATH_PREFIX: "audio-files/"
        volumes:
            - type: bind
              source: ./../podcast-fetch-episode/bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./../podcast-fetch-episode/src/
              target: /opt/mediacloud/src/podcast-fetch-episode/
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/
        depends_on:
            - postgresql-pgbouncer
            - rabbitmq-server

    podcast-submit-operation:
        image: gcr.io/mcback/podcast-submit-operation:latest
        init: true
        stop_signal: SIGKILL
        environment:
            MC_PODCAST_GC_AUTH_JSON_BASE64: "${MC_PODCAST_GC_AUTH_JSON_BASE64}"
        volumes:
            - type: bind
              source: ./../podcast-submit-operation/bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./../podcast-submit-operation/src/
              target: /opt/mediacloud/src/podcast-submit-operation/
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/
        depends_on:
            - postgresql-pgbouncer
            - rabbitmq-server

    postgresql-pgbouncer:
        image: gcr.io/mcback/postgresql-pgbouncer:latest
        init: true
        stop_signal: SIGKILL
        expose:
            - 6432
        volumes:
            - type: bind
              source: ./../postgresql-pgbouncer/conf/
              target: /etc/pgbouncer/
        depends_on:
            - postgresql-server

    postgresql-server:
        image: gcr.io/mcback/postgresql-server:latest
        init: true
        stop_signal: SIGKILL
        expose:
            - 5432
        volumes:
            - type: bind
              source: ./../postgresql-server/bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./../postgresql-server/schema/
              target: /opt/mediacloud/schema/
            - type: bind
              source: ./../postgresql-server/conf/
              target: /etc/postgresql/11/main/

    rabbitmq-server:
        image: gcr.io/mcback/rabbitmq-server:latest
        init: true
        stop_signal: SIGKILL
        expose:
            - 5672
            - 15672
        volumes:
            - type: bind
              source: ./../rabbitmq-server/conf/
              target: /etc/rabbitmq/
