#
# Docker and containerd.io versions to install
#
# Older Docker versions have caching discrepancies, so we try to run the same version everywhere.
#
# Get a list of available versions by running:
#
#     apt-cache madison docker-ce
#     apt-cache madison containerd.io
#
docker_version: "19.03.13"
containerd_io_version: "1.3.7-1"

#
# Docker daemon configuration
#
# Dictionary gets converted to JSON and stored to /etc/docker/daemon.json.
#
docker_daemon_config:

  # Increase default shutdown timeout:
  shutdown-timeout: 60

  # Log to JSON files that can be later ingested by elk-filebeat
  log-driver: "json-file"

  # All log-opts values have to be strings!
  log-opts:
    max-size: "100m"
    max-file: "4"
